### ISSUE TITLE
实在不好意思，我想知道您vgg_image_feature中的all.txt文件在哪里

### ISSUE THREAD

**Issue by T1aNS1R** [jlfu/NERmultimodal#10]
实在不好意思，我想知道您vgg_image_feature中的all.txt文件在哪里

**Comment by dwchen123** [comment]
你好，请问你有改动 vgg_image_feature.py里的代码吗？我的这个运行报错，我看了一下是get_features(model, 30, im)这个函数里的错，但不知道怎么改

**Comment by T1aNS1R** [comment]
没有，我已经不关注这篇文章了，另一篇可以复现出来结果，如果您也对多模态这个方向有兴趣，您可以加我微信tianyu6665，我们交流交流
